Repository Ky7Org/react-native-seminar, pull requests merged in 2021-09, with the labels that each got.

#8 FUSE-9 add delete modal
  App.tsx
  components/Admin/ManageUser/DeleteUserScreen/index.tsx
  components/Admin/ManageUser/EditUserScreen/index.tsx
  package.json
  yarn.lock
Labels: ready to merge

#9 FUSE-9 add onPress for modals
  components/Admin/ManageUser/EditUserScreen/index.tsx
Labels: ready to review, ready to merge

#3 FUSE-8 Implement Update User Screen
  App.tsx
  components/Admin/ManageUser/DeleteUserScreen/index.tsx
  components/Admin/ManageUser/EditUserScreen/index.tsx
  constants.ts
  package.json
  yarn.lock
Labels: ready to review, ready to merge

#10 [FUSE-13] Implementing Sidebar Menu (Drawer Navigation) for Users Management
  App.tsx
  assets/dead_pool.jpg
  components/Admin/ManageUser/CreateUserScreen/index.tsx
  components/Admin/ManageUser/CreateUserScreen/styles/index.css.tsx
  components/Admin/ManageUser/UserDetailScreen/constants/index.ts
  components/Admin/ManageUser/UserDetailScreen/constants/index.tsx
  components/Admin/ManageUser/UserDetailScreen/index.tsx
  components/Admin/ManageUser/UserDetailScreen/styles/index.css.tsx
  components/Admin/ManageUser/UserListScreen/index.tsx
  components/Admin/ManageUser/UserListScreen/styles/index.css.tsx
  components/Drawer/DrawerContent.tsx
  constants.ts
  models/users.model.ts
  navigations/App/AppStack.tsx
  navigations/App/index.ts
  navigations/Home/GlobalDrawer.tsx
  navigations/Home/HomeStack.tsx
  navigations/Home/index.ts
  navigations/UsersManagement/CreateAccountStack.tsx
  navigations/UsersManagement/UserListStack.tsx
  navigations/UsersManagement/UsersDetailStack.tsx
  navigations/index.ts
  package-lock.json
  package.json
  yarn.lock
Labels: ready to review, do not merge

#5 [FUSE-10] - Implementing Authentication for Users Management
  App.tsx
  components/Admin/LoginScreen/index.tsx
  components/Admin/LoginScreen/styles.tsx
  package-lock.json
  package.json
  yarn.lock
Labels: ready to review, do not merge, WIP

#13 [FUSE-18] - Application suddenly closed cause by Create New Account S…
  components/Guest/RegisterScreen/index.tsx
Labels: ready to review, ready to merge

#14 FUSE-30: [PRM391] - Clean up CSS variables
  components/Admin/ManageUser/DeleteUserScreen/index.tsx
  components/Admin/ManageUser/DeleteUserScreen/styles/index.css.tsx
  components/Admin/ManageUser/EditUserScreen/index.tsx
  components/Admin/ManageUser/EditUserScreen/styles/index.css.tsx
  components/Admin/ManageUser/UserDetailScreen/index.tsx
  components/Admin/ManageUser/UserDetailScreen/styles/index.css.tsx
  components/Admin/ManageUser/UserListScreen/index.tsx
  components/Admin/ManageUser/UserListScreen/styles/index.css.tsx
  components/Guest/LoginScreen/index.tsx
  components/Guest/LoginScreen/styles/index.css.tsx
  components/Guest/RegisterScreen/index.tsx
  components/Guest/RegisterScreen/styles/index.css.tsx
  services/users.service.ts
Labels: ready to review, ready to merge

#15 FUSE-25: [PRM391] - Update README for React Native Seminar to introduce how to use
  README.md
Labels: ready to review, ready to merge

#16 FUSE-23: [PRM391] - Cannot format Datetime using Intl.DateTimeFormat on some Android APIs
  components/Admin/ManageUser/UserDetailScreen/index.tsx
  package.json
  yarn.lock
Labels: ready to review, ready to merge

#17 FUSE-32: [PRM391] - View User Detail when authenticated user click a specific user on the list
  components/Admin/ManageUser/UserDetailScreen/index.tsx
  components/Admin/ManageUser/UserListScreen/index.tsx
  navigations/Home/GlobalDrawer.tsx
  navigations/users-list-stack.tsx
Labels: ready to review, ready to merge

#18 FUSE-26: [PRM391] - Implementing Password Validator at Sign-Up Screen
  components/Guest/RegisterScreen/index.tsx
  components/Guest/RegisterScreen/styles/index.css.tsx
Labels: ready to review, ready to merge

#19 FUSE-29: [PRM391] - Only input one character for search bar in User list view
  components/Admin/ManageUser/UserListScreen/index.tsx
  constants.ts
  navigations/users-list-stack.tsx
Labels: ready to review, ready to merge

#20 FUSE-33: [PRM391] - The params of route is undefined when the authenticated user navigates to the ‘My Information’
  components/Admin/ManageUser/UserDetailScreen/index.tsx
  components/Drawer/BodyDrawerContent.tsx
Labels: ready to review, ready to merge

#21 FUSE-24: [PRM391] - User Role pill is not switched to User when the authenticated user having User role
  components/Admin/ManageUser/UserListScreen/index.tsx
Labels: ready to review, ready to merge
